# SOPS configuration for secret management
keys:
  - &t490 age1j5stf7fgf2gfwptzn43tzma3cp7chzhuz025f98efefh4nzzuvjqgvz293

creation_rules:
  - path_regex: secrets/secrets\.yaml$
    key_groups:
      - age:
          - *t490
